// Hand-written answers to the brief's 10 questions.
//
// WHY THIS FILE EXISTS: until 2026-08-23 the dashboard reported, for every
// question, a fill rate and nothing else — Q1 ("Why do users add products to
// their wishlist?") displayed "save_motivation captured in 8/1234
// extractions". That is a measurement of how much data exists, not an answer.
// The engine could say how much it had found and never what it concluded.
//
// AUTHORSHIP, stated plainly because it matters for how these should be read:
// every line below is written by the analyst from reading the extracted
// records directly, NOT generated by an LLM. Synthesising across 1,234
// records while holding the no-monetary-levers constraint and the
// friction/praise distinction is exactly the task where a one-shot model call
// produces fluent, unfalsifiable mush. Hand-writing it means each claim is
// traceable to records a reader can pull up, and wrong claims are my error
// rather than an unattributable model artifact.
//
// SCOPE GUARD (problem_statement.md §13): these are ANSWERS, not solutions.
// This engine's job ends at identify / quantify / compare. Where the corpus
// shows people routing around a gap, that is reported as an OBSERVED
// workaround — evidence of an unmet need — never as a proposed feature.
// Solution design is a later stage gated on the interviews.
//
// GROUNDING RULE: every claim here traces to records in
// pipeline/data/extracted/extracted.jsonl. Counts are stated so they can be
// checked, and where the evidence is too thin to support an answer this says
// so instead of reaching.

export interface BriefAnswer {
  id: number;
  question: string;
  /** The answer in one line. Null when the corpus genuinely cannot answer it. */
  answer: string | null;
  /** The reasoning, with the evidence it rests on. */
  detail: string;
  /** Distinct mechanisms found, most-evidenced first. */
  mechanisms?: { label: string; note: string }[];
  /** How much this rests on — stated so a reader can discount appropriately. */
  evidenceNote: string;
  /** Where the answer is unreliable, contaminated, or thin. Never omitted
   * when one exists: a caveat a reader has to discover for themselves is
   * worse than no answer. */
  caveat?: string;
  /** Which lens actually produced the answer. */
  source: "Reddit (prospective)" | "App/Play (retrospective)" | "Both lenses" | "Neither — handed to interviews";
}

/** The single most important structural finding, and the reason several
 * answers below lean almost entirely on 37 Reddit records rather than 1,197
 * App/Play ones. */
export const LENS_FINDING = {
  headline: "The two sources answer different questions, and only one of them is about wishlists.",
  detail:
    "App/Play reviews are post-purchase satisfaction data: 1,197 records, 11.3% carrying any friction signal, and the friction they do carry is overwhelmingly about delivery, service and product quality — what happened AFTER the buy decision. Reddit is 37 records at 86.5% friction, and it is where wishlist hesitation is actually narrated, because people go there to think out loud while still deciding. Volume and relevance point in opposite directions here, so several answers below rest on double-digit Reddit counts rather than four-digit App/Play ones. That is the honest weighting, not a shortage of effort on the larger source.",
};

export const BRIEF_ANSWERS: BriefAnswer[] = [
  {
    id: 1,
    question: "Why do users add products to their wishlist?",
    answer:
      "Predominantly as a price-watching tool — the wishlist is used to hold an item until it gets cheaper, not as a queue of things about to be bought.",
    detail:
      "Of the 8 records that state a save motivation, 4 describe saving specifically to track price: holding sneakers at ~₹1,300 waiting for a drop, shortlisting a dress in the days before an announced sale, keeping a standing restock list to convert when a sale lands, holding a long-wanted perfume until the price justified it. A separate and distinct motive is aspirational: saving against an idealised future occasion or self (\"a cafe day, a trip\") rather than a scheduled event. These two motives predict very different conversion behaviour, which is why they are reported separately rather than merged into a single \"intent to buy later\".",
    mechanisms: [
      { label: "Price-watching", note: "Item is parked deliberately until a price drop or sale event — the save IS the tracking mechanism. 4 of 8 records." },
      { label: "Aspirational / idealised-self saving", note: "Saved against an imagined occasion or version of oneself, not a real planned event. Directly predicts non-conversion." },
      { label: "Replenishment queue", note: "A standing to-buy list of already-decided products, converted when the current one runs out." },
    ],
    evidenceNote: "8 records state a save motivation (7 Reddit, 1 App/Play). Small, but the price-watching pattern is consistent and corroborated independently by Q4's deferral evidence.",
    caveat:
      "8 records cannot establish proportions for a user base. Read this as \"these motives exist and recur\", not \"most users save for price\". The single App/Play record here (\"save my time and have some peace of mind\") is not about wishlisting at all and was disregarded.",
    source: "Reddit (prospective)",
  },
  {
    id: 2,
    question: "What prevents wishlisted products from being purchased?",
    answer:
      "Six distinct blockers, and only one of them is about the product itself — the rest are about the decision, the platform, or the price moving.",
    detail:
      "The 26 Reddit blocker records separate cleanly into recurring mechanisms rather than one dominant cause. Notably, the strongest single blocker is structural rather than psychological: Myntra's wishlist caps at ~1,000 items and heavy users hit it, at which point saving a new item requires deleting an old one. The second is a timing failure specific to price-watching — several users held items for an announced sale and watched prices RISE when it started (₹1,300 → ₹1,800), which inverts the entire reason they waited.",
    mechanisms: [
      { label: "Wishlist capacity cap", note: "The ~1,000-item limit blocks further saving outright. A platform constraint, not a preference — and users describe hitting it without warning." },
      { label: "No mapping to a real occasion", note: "Reviewed later, saved items don't correspond to anything actually scheduled. Surfaces at checkout, where carts get trimmed hard." },
      { label: "Price-watching backfire", note: "Waited for a sale, price went up instead. The deferral doesn't merely fail — it actively costs the purchase." },
      { label: "Choice overload from undirected browsing", note: "\"Like 100 things, dislike another 100, eventually won't buy anything.\" Volume itself prevents convergence." },
      { label: "Category-specific confidence", note: "Basics (tees, socks) bought confidently; shirts, casual shoes and perfume described as much harder to judge unseen." },
      { label: "Brand-level trust, not platform-level", note: "Scepticism attaches to specific unfamiliar/imported marketplace brands, distinct from trust in Myntra generally." },
    ],
    evidenceNote: "26 Reddit records carrying an explicit unresolved blocker (72% of the Reddit lens).",
    caveat:
      "The 26 App/Play `hesitation_signal` records were reviewed and largely excluded from this answer: they are dominated by fragments and generic app complaints (\"coupon not allowed\", \"worst delivery service\", and several one-word captures) rather than wishlist hesitation. Counting them alongside the Reddit records would inflate the apparent evidence base without adding signal.",
    source: "Reddit (prospective)",
  },
  {
    id: 3,
    question: "What uncertainties remain after finding a product they like?",
    answer:
      "Whether it will actually get worn — not whether it will arrive or fit. The dominant residual doubt is occasion and versatility, not product quality.",
    detail:
      "This question draws on the same records as Q2, but the uncertainty-shaped subset points somewhere specific. Users describe liking an item and still not buying because they cannot place it in their real life: saved items don't map to scheduled events, and at checkout each one gets re-evaluated against actual planned occasions and most are removed. The observed workarounds corroborate this from the other direction — people invented explicit versatility tests (see Q10), which is what you build when the open question is \"will I wear this enough\", not \"is this good\".",
    mechanisms: [
      { label: "Occasion uncertainty", note: "Cannot place the item against a real, scheduled event. The most-evidenced residual doubt." },
      { label: "Versatility uncertainty", note: "Unsure it combines with clothes already owned — hence self-imposed outfit-count rules." },
      { label: "Sight-unseen judgement risk", note: "Concentrated in specific categories (shirts, footwear, fragrance) rather than uniform." },
    ],
    evidenceNote: "Same 26-record blocker base as Q2, filtered to uncertainty-shaped statements; reinforced by 5 of the 19 workaround records.",
    caveat:
      "Q2 and Q3 share an evidence base, so they are not independent findings and should not be presented as two separate confirmations of the same point.",
    source: "Reddit (prospective)",
  },
  {
    id: 4,
    question: "What causes users to postpone a purchase?",
    answer:
      "Waiting for a price drop, almost to the exclusion of everything else — 7 of 9 genuine deferral statements are price-timing.",
    detail:
      "Where a user explains what they are waiting FOR, the answer is nearly always a better price: watching for a price to return to a previous low, holding until a sale goes live, monitoring for a month to catch the bottom, deferring an order to \"tomorrow\". The behaviour is sophisticated — one user runs automated multi-site price monitoring, another checks BuyHatke price history before any purchase — and it is frequently self-defeating, since several report the price rising while they waited.",
    mechanisms: [
      { label: "Price-drop waiting", note: "7 of 9 deferral statements. Often paired with external price-history tooling." },
      { label: "Sale-event anchoring", note: "Holding specifically until a known event (End of Reason Sale) — which also concentrates the risk of the backfire in Q2." },
      { label: "Replenishment gating", note: "Deliberately not buying until the existing product runs out." },
    ],
    evidenceNote: "9 Reddit records state an explicit deferral trigger.",
    caveat:
      "IMPORTANT MEASUREMENT ERROR in the headline number. The coverage figure for this question pools `deferral_trigger` with `delay_signal`, but the 51 App/Play `delay_signal` records are almost entirely DELIVERY delays (\"17 days delayed\", \"supposed to be delivered on 14th Aug\") — shipping complaints, not purchase postponement. The real evidence for this question is the 9 Reddit records, not 60. The pooled count overstates coverage roughly sixfold and should be corrected in score.py's QUESTION_FIELDS mapping.",
    source: "Reddit (prospective)",
  },
  {
    id: 5,
    question: "How do users compare multiple shortlisted products?",
    answer:
      "By staging comparisons the interface doesn't support — most visibly, using the cart itself as a side-by-side comparison surface.",
    detail:
      "The clearest mechanism found: a user deliberately adds several close variants of the same item type to the cart at once specifically so they render side by side, then removes the losers. That is a comparison tool improvised out of a purchasing surface. Beyond it, comparison is mostly cross-platform and price-led — checking Nykaa, Amazon, Flipkart for the same item, tracking one item's price across five days, benchmarking a fragrance's wear time against a Zara product to decide the price wasn't justified.",
    mechanisms: [
      { label: "Cart-as-comparison-surface", note: "Multiple close variants added together purely to see them side by side, then culled." },
      { label: "Cross-platform price checking", note: "Same item priced on Nykaa/Amazon/Flipkart before committing." },
      { label: "Longitudinal price tracking", note: "One item watched across days or weeks rather than compared against alternatives at a moment." },
    ],
    evidenceNote: "23 records, but only ~8 describe a real comparison method; the App/Play entries are mostly vague (\"Compared Amazon and other platforms\").",
    caveat:
      "The original design routed this question to interviews, predicting comparison is rarely narrated publicly. That prediction held: the mechanisms above are real but rest on single-digit record counts, and the interviews remain the primary instrument here.",
    source: "Reddit (prospective)",
  },
  {
    id: 6,
    question: "What information do users seek outside Myntra?",
    answer:
      "Style inspiration and price history — two needs Myntra doesn't serve, so users assemble them elsewhere and return.",
    detail:
      "Two distinct off-platform jobs appear. First, style/inspiration: users build Pinterest boards or cycle through Instagram to work out what they want BEFORE they can search Myntra effectively — one explicitly frames maintaining a Pinterest board as a workaround for Myntra having no equivalent, which makes this an observed unmet need rather than a preference. Second, verification: BuyHatke for price history, Fragrantica for fragrance reviews, Nykaa/Amazon/Flipkart for price comparison, and Reddit itself as a pre-purchase filter (\"which of these deals are actually real\").",
    mechanisms: [
      { label: "Style inspiration (Pinterest/Instagram)", note: "Done before search, because the user can't specify what they want yet. Explicitly described as a workaround for a missing in-app capability." },
      { label: "Price-history verification (BuyHatke)", note: "Used to judge whether a displayed discount is genuine — the trust gap made concrete." },
      { label: "Product validation (Fragrantica, Nykaa, community)", note: "Third-party reviews trusted over on-platform ones, especially where authenticity is in doubt." },
    ],
    evidenceNote: "13 records, 11 of them Reddit.",
    caveat:
      "The engine found this in 13 of 1,234 records (1.1%), while published literature puts webrooming near-universal. That gap is far more likely a text-availability artifact — people rarely narrate routine cross-checking in a review — than evidence the behaviour is rare. Treat the mechanisms as real and the rate as unmeasured.",
    source: "Reddit (prospective)",
  },
  {
    id: 7,
    question: "Role of fit, size, styling, price, reviews, occasion, social validation",
    answer:
      "Quality and price dominate what shoppers volunteer, but the factors that BLOCK a wishlist purchase are different from the ones they talk about most.",
    detail:
      "798 factor mentions across 1,234 records bucket into 9 categories, led by Quality & Authenticity and Price & Value. But this is the one question where the friction/praise split matters most: the highest-volume factors are largely raised in PRAISE (people saying quality was good, price was worth it), while the factors that actually appear in blocker records are occasion, versatility, and trust. Volume of mention and power to block are not the same thing, and the ranked opportunity areas deliberately weight the latter.",
    mechanisms: [
      { label: "Most-mentioned", note: "Quality & Authenticity, then Price & Value — but predominantly as satisfaction, not friction." },
      { label: "Most-blocking", note: "Occasion fit and styling versatility, which appear far less often but almost exclusively in unresolved-blocker records." },
      { label: "Price, two ways", note: "Appears both as satisfaction (\"value for money\") and as the single most common deferral cause — the same factor on both sides." },
    ],
    evidenceNote: "798 factor mentions across the full corpus; the strongest-covered of the 10 questions.",
    caveat:
      "Factor categorisation uses a visible keyword-marker lexicon, not a trained model; ~12.6% of mentions fall outside the 9 buckets and are left unclassified rather than force-fitted.",
    source: "Both lenses",
  },
  {
    id: 8,
    question: "Genuine purchase intent vs. bookmarking?",
    answer:
      "Both exist and are distinguishable in the text — but on the prospective lens, saving-for-later is the more common stance.",
    detail:
      "`intent_signal` resolves to an explicit stance in a large share of records and is the only required field in the schema, so coverage is strong. The more useful reading is per-lens: App/Play records skew buy-intent because everyone in that sample already bought, which is a structural artifact rather than a finding. Reddit — the people actually mid-decision — skews save-for-later. Combined with Q1, the picture is that a meaningful share of wishlist adds are explicitly NOT queued purchases: they are price bets and aspirational saves.",
    mechanisms: [
      { label: "Buy-intent", note: "Dominant on App/Play, but tautologically so — that lens only contains completed purchases." },
      { label: "Save-for-later", note: "The more common explicit stance among people still deciding." },
      { label: "Not-determinable", note: "The largest bucket corpus-wide. Means no textual evidence either way, NOT 'browsing' — a distinction that must not be collapsed." },
    ],
    evidenceNote: "Resolved on a large share of 1,234 records; required field, so no missing-data gaps.",
    caveat:
      "A tempting move is relabelling these as Browser/Considerer/Ready-Buyer personas. That was evaluated and rejected: not-determinable is ~78% of the corpus and means absent evidence, so treating it as a behavioural segment would convert missing data into a confident claim.",
    source: "Both lenses",
  },
  {
    id: 9,
    question: "How do behaviours differ across segments?",
    answer:
      "Only one segment is genuinely visible in the data — the heavy wishlister — and it is visible mainly because it hits a wall the platform imposes.",
    detail:
      "Public text almost never states demographics, and the 18 records here confirm it. What does recur is a self-identified heavy/frequent wishlister who has hit the ~1,000-item cap — a segment defined by behaviour rather than demography, and the only one with more than a couple of supporting records. Isolated others appear once each: someone working in clothing production applying professional fabric scrutiny, a self-described sale-price-watcher.",
    mechanisms: [
      { label: "Heavy wishlister", note: "Recurring and behaviourally defined. Hits the capacity cap, deletes to make room — the clearest segment-specific blocker in the corpus." },
      { label: "Sale-price-watcher", note: "Overlaps heavily with the Q1/Q4 price-watching motive; may be the same behaviour rather than a distinct group." },
    ],
    evidenceNote: "18 records; roughly half are unusable (an App/Play entry reading only \"Manipur\", another that is a full complaint with no segment content).",
    caveat:
      "This question was routed to the interviews from the original design, and that routing stands. The engine can name one behavioural segment; it cannot compare behaviour ACROSS segments, which is what the question actually asks.",
    source: "Neither — handed to interviews",
  },
  {
    id: 10,
    question: "What unmet needs emerge consistently?",
    answer:
      "Four, each evidenced by users building their own workaround — the strongest unmet-need signal available, since someone paid real effort to route around the gap.",
    detail:
      "The 19 workaround records are the most decision-useful material in the corpus, because a workaround is a need someone already tried to meet themselves. They cluster into four gaps. Reported here as observed behaviour, not as feature proposals — solution design sits outside this engine's scope.",
    mechanisms: [
      { label: "No versatility check before buying", note: "Users invented explicit rules — \"if it can't make 4 outfits from clothes I own, it goes\", \"must be styleable two ordinary ways\". A test they run manually because nothing supports it." },
      { label: "No in-app inspiration surface", note: "Pinterest boards maintained outside Myntra purely to work out what to search for, described explicitly as a workaround for its absence." },
      { label: "Review trust is manual work", note: "Sorting reviews by newest and trusting only those with customer photos, on the reasoning that fabric quality drifts between production batches — the aggregate star rating treated as unreliable." },
      { label: "Wishlist capacity managed by hand", note: "Deleting older saved items to free room, and checking external price-history sites because on-platform pricing isn't trusted." },
    ],
    evidenceNote: "19 workaround records, 17 of them Reddit.",
    caveat:
      "Small n, and self-selected: people who build workarounds and then write about them are unusually engaged. These are real needs; their prevalence is unmeasured.",
    source: "Reddit (prospective)",
  },
];

/** What the answers say when read together, rather than one at a time. */
export const CROSS_CUTTING_FINDINGS = [
  "Price-watching is the through-line. It is the main reason people save (Q1), the main reason they postpone (Q4), a major comparison mode (Q5), and a driver of off-platform research (Q6) — and it regularly backfires when prices rise during the sale that was being waited for (Q2). It is also the one lever this project cannot pull, since monetary incentives are excluded by the brief.",
  "The blockers are mostly not about the product. Capacity limits, occasion mismatch, choice overload and price timing are decision and platform problems. Fit and comfort — the factor most associated with online fashion — appears in the corpus almost entirely as PRAISE, and its theme carries zero blocker-bearing records.",
  "Users build tools the platform doesn't give them. Versatility rules, review-photo filtering, external Pinterest boards, external price history, manual wishlist pruning. Each is an unmet need someone already spent effort on.",
  "The wishlist is being used as a price-tracking instrument more than a purchase queue. That reframes the business metric: a saved item is often a bet on a future price, not a deferred intent to buy at today's price.",
];
