"use client";

import StatusPill, { Status } from "../charts/StatusPill";
import ConfidenceRing from "../charts/ConfidenceRing";
import { QuestionCoverageRow } from "@/lib/types";
import { BRIEF_ANSWERS, CROSS_CUTTING_FINDINGS, LENS_FINDING } from "@/lib/briefAnswers";

// All 10 brief questions with what was actually found for each — the real top
// phrases from the extraction field that answers it, not just a fill-rate.
// A coverage view that only reports "captured in 3/578" tells the reader how
// MUCH was found but never WHAT, which is the part that matters.
export default function QuestionCoverageDetail({ rows }: { rows: QuestionCoverageRow[] }) {
  const strong = rows.filter((r) => r.confidence === "Strong").length;
  const medium = rows.filter((r) => r.confidence === "Medium").length;
  const weak = rows.filter((r) => r.confidence === "Weak").length;

  return (
    <div>
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="max-w-lg text-sm leading-relaxed text-ink-soft">
          The brief poses 10 questions. An engine that claims to answer all of them equally well from public text is
          less trustworthy than one that knows its own blind spots — so each row shows the answer, what it rests on,
          and where it&apos;s unreliable.
        </p>
        <ConfidenceRing strong={strong} medium={medium} weak={weak} />
      </div>

      <div className="mb-4 rounded-xl border border-brand/30 bg-brand-soft/20 p-3.5">
        <p className="mb-1 text-sm font-semibold text-ink">{LENS_FINDING.headline}</p>
        <p className="text-xs leading-relaxed text-ink-soft">{LENS_FINDING.detail}</p>
      </div>

      <p className="mb-3 text-[11px] leading-relaxed text-ink-faint">
        <span className="font-semibold text-ink-soft">On the answers below:</span> they are written by the analyst from
        reading the extracted records directly — not generated by a model. Per this engine&apos;s scope, they identify
        and quantify; they do not propose solutions. Where people built their own workaround, that is reported as
        observed evidence of an unmet need.
      </p>

      <ul className="divide-y divide-line">
        {rows.map((row, idx) => {
          // Match on the question's own leading number ("4. What causes...")
          // rather than array position, so a reordering in score.py can't
          // silently attach the wrong analysis to a question. Falls back to
          // position only if the number can't be parsed.
          const parsed = Number.parseInt(row.question, 10);
          const analysis =
            BRIEF_ANSWERS.find((a) => a.id === parsed) ?? (Number.isNaN(parsed) ? BRIEF_ANSWERS[idx] : undefined);
          return (
            <li key={row.question} className="py-3.5">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold text-ink">{row.question}</p>
                  <p className="mt-0.5 text-xs text-ink-soft">
                    {row.finding}
                    {row.coveragePct !== undefined && (
                      <span className="text-ink-faint"> · {row.coveragePct}% coverage</span>
                    )}
                  </p>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <StatusPill status={row.confidence as Status} />
                  <span className="rounded-full border border-line px-2 py-0.5 text-[11px] font-semibold text-ink-soft nav-tab">
                    {row.answeredBy}
                  </span>
                </div>
              </div>

              {analysis && (
                <div className="mt-2.5 rounded-xl border border-line bg-white p-3">
                  {analysis.answer ? (
                    <p className="text-sm font-semibold leading-snug text-ink">{analysis.answer}</p>
                  ) : (
                    <p className="text-sm font-semibold leading-snug text-ink-faint">
                      The corpus cannot answer this one.
                    </p>
                  )}
                  <p className="mt-1.5 text-xs leading-relaxed text-ink-soft">{analysis.detail}</p>

                  {analysis.mechanisms && analysis.mechanisms.length > 0 && (
                    <ul className="mt-2 space-y-1.5">
                      {analysis.mechanisms.map((m) => (
                        <li key={m.label} className="flex gap-2 text-xs">
                          <span className="mt-0.5 shrink-0 text-brand" aria-hidden>
                            →
                          </span>
                          <span className="text-ink-soft">
                            <span className="font-semibold text-ink">{m.label}: </span>
                            {m.note}
                          </span>
                        </li>
                      ))}
                    </ul>
                  )}

                  <div className="mt-2.5 flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-line pt-2 text-[11px] text-ink-faint">
                    <span className="rounded-full border border-line px-2 py-0.5 font-semibold">{analysis.source}</span>
                    <span>{analysis.evidenceNote}</span>
                  </div>

                </div>
              )}

              {row.insights && row.insights.length > 0 ? (
                <div className="mt-2 rounded-xl bg-surface p-3">
                  <p className="mb-1.5 text-[10px] font-semibold uppercase text-ink-faint nav-tab">
                    What the corpus actually said
                    {row.fields && <span className="ml-1 font-normal normal-case">· from {row.fields.join(", ")}</span>}
                  </p>
                  <ul className="space-y-1">
                    {row.insights.map((ins) => (
                      <li key={`${ins.field}-${ins.phrase}`} className="flex gap-2 text-xs text-ink-soft">
                        <span className="shrink-0 font-semibold text-ink-faint">{ins.count}×</span>
                        <span>{ins.phrase}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : (
                <p className="mt-2 rounded-xl bg-surface px-3 py-2 text-xs text-ink-faint">
                  No phrases extracted for this question&apos;s field
                  {row.fields && <> (<code className="text-[11px]">{row.fields.join(", ")}</code>)</>} — handed to the
                  interview stage rather than answered thinly.
                </p>
              )}
            </li>
          );
        })}
      </ul>

      {/* Read together rather than one at a time — the patterns that only
          show up across questions, which per-question rows can't surface. */}
      <section className="mt-5 rounded-2xl border border-brand/30 bg-brand-soft/20 p-4">
        <p className="mb-2 text-[11px] font-semibold uppercase text-ink-faint nav-tab">
          Reading the ten answers together
        </p>
        <ul className="space-y-2">
          {CROSS_CUTTING_FINDINGS.map((f) => (
            <li key={f.slice(0, 40)} className="flex gap-2 text-sm leading-relaxed text-ink-soft">
              <span className="mt-1 shrink-0 text-brand" aria-hidden>
                ●
              </span>
              <span>{f}</span>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
